const ADMIN_USER='admin';
const ADMIN_PASS='admin';
let adviceTopic='';
let deferredInstallPrompt=null;

function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function toggleMobileNav(){const nav=document.getElementById('mobile-nav');if(!nav)return;nav.classList.toggle('show');document.body.classList.toggle('nav-open',nav.classList.contains('show'));const buttons=document.querySelectorAll('.menu-btn,.mobile-menu-toggle');buttons.forEach(b=>b.setAttribute('aria-expanded',nav.classList.contains('show')))}
function closeMobileNav(){document.getElementById('mobile-nav')?.classList.remove('show');document.body.classList.remove('nav-open');document.querySelectorAll('.menu-btn,.mobile-menu-toggle').forEach(b=>b.setAttribute('aria-expanded','false'))}
function openModal(html){const modal=document.getElementById('modal');if(!modal)return;document.getElementById('modal-content').innerHTML=html;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function closeModal(){const modal=document.getElementById('modal');if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
window.addEventListener('click',e=>{if(e.target.id==='modal')closeModal();if(e.target.classList.contains('mobile-backdrop'))closeMobileNav()})
function chooseTopic(topic){closeMobileNav();document.getElementById('advice')?.scrollIntoView({behavior:'smooth'});setAdviceTopic(null,topic);toast(`Let's talk about ${topic.toLowerCase()}.`)}
function setAdviceTopic(button,topic){adviceTopic=topic;document.querySelectorAll('#topic-pills button').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active')}
function submitAdvice(){const text=document.getElementById('advice-text')?.value.trim();const urgency=document.getElementById('advice-urgency')?.value;if(!text||text.length<10){toast('Tell us a little more so we can guide you.');return}const request={topic:adviceTopic||'General guidance',message:text,urgency,time:new Date().toISOString(),name:localStorage.getItem('joboTeenName')||'Teen'};const requests=JSON.parse(localStorage.getItem('mentorRequests')||'[]');requests.push(request);localStorage.setItem('mentorRequests',JSON.stringify(requests));const result=document.getElementById('advice-result');if(result){result.hidden=false;result.innerHTML='<b>Your request is saved privately on this device.</b><br>For a response from a real mentor, connect JoboTeen to a secure backend.'}document.getElementById('advice-text').value='';toast('Your guidance request has been recorded.')}
function openProfile(){const name=localStorage.getItem('joboTeenName')||'';openModal(`<span class="eyebrow">OPTIONAL PROFILE</span><h2>Keep your experience personal.</h2><p>You can use JoboTeen without an account. This optional profile is stored locally on this device.</p><div class="modal-form"><input id="profile-name" value="${escapeHtml(name)}" placeholder="Your first name or nickname"><input id="profile-goal" value="${escapeHtml(localStorage.getItem('joboTeenGoal')||'')}" placeholder="What do you want to work on?"><button class="primary-btn" onclick="saveProfile()">Save my profile</button></div>`)}
function saveProfile(){const name=document.getElementById('profile-name').value.trim();const goal=document.getElementById('profile-goal').value.trim();if(name)localStorage.setItem('joboTeenName',name);if(goal)localStorage.setItem('joboTeenGoal',goal);closeModal();toast('Your optional profile is saved on this device.')}
function openMentor(type){openModal(`<span class="eyebrow">MENTORSHIP</span><h2>${escapeHtml(type)}</h2><p>Tell us what you would like guidance with. You don't need an account to start.</p><div class="modal-form"><textarea id="mentor-message" rows="6" placeholder="What would you like help with?"></textarea><button class="primary-btn" onclick="sendMentorRequest('${escapeJs(type)}')">Send request →</button></div>`)}
function sendMentorRequest(type){const message=document.getElementById('mentor-message').value.trim();if(message.length<10){toast('Please add a little more detail.');return}const requests=JSON.parse(localStorage.getItem('mentorRequests')||'[]');requests.push({mentor:type,message,urgency:'General guidance',time:new Date().toISOString(),name:localStorage.getItem('joboTeenName')||'Anonymous teen'});localStorage.setItem('mentorRequests',JSON.stringify(requests));closeModal();toast('Request saved. A mentor workflow can be connected by the administrator.')}
function openResource(type){const content={study:['Study Skills','Try one focused 25-minute session, then take a short break. Active recall means closing your notes and explaining what you remember. Spaced repetition means revisiting difficult material over time.'],subjects:['Subject Help','Start with the exact question you cannot answer. Break it into known information, unknown information and the concept you need to review.'],life:['Life Skills','Healthy boundaries, clear communication and self-awareness are skills you can practise. Start with one situation and identify what you can control.'],career:['Career Pathways','Think in terms of interests, strengths and problems you enjoy solving. You do not need to choose your entire future today.']};const [title,text]=content[type]||content.life;openModal(`<span class="eyebrow">JOBOTEEN GUIDE</span><h2>${title}</h2><p>${text}</p><div class="modal-form"><button class="primary-btn" onclick="closeModal();document.getElementById('advice').scrollIntoView({behavior:'smooth'})">I want personalised guidance →</button></div>`)}
function readStory(title){const stories={"The Dreamer":'Amira keeps drawing even when classmates mock her. The lesson: criticism can hurt, but it does not have to decide what you become.',"The Choice":'Two friends pressure you to choose a side. Before reacting, consider what is fair, what is safe and what future version of you will respect.',"Behind the Message":'A short message can hide a complicated feeling. Pause before reacting and ask what you may not know yet.'};openModal(`<span class="eyebrow">MIND LIBRARY</span><h2>${escapeHtml(title)}</h2><p>${stories[title]||'A reflection story about growing, choosing and learning.'}</p><p><b>Reflect:</b> What would you do? What could happen next? What would you tell a friend in the same situation?</p><button class="primary-btn" onclick="closeModal();document.getElementById('advice').scrollIntoView({behavior:'smooth'})">Talk it through →</button>`)}
function openGame(path){openModal(`<span class="eyebrow">FUN + LEARNING</span><h2>Game ready</h2><p>Open the cognitive game in a focused window.</p><button class="primary-btn" onclick="window.location.href='${escapeJs(path)}'">Start game →</button>`)}
function openAdminLogin(){openModal(`<span class="eyebrow">RESTRICTED ACCESS</span><h2>Admin dashboard</h2><p>This area is for JoboTeen administrators.</p><div class="modal-form"><input id="admin-user" autocomplete="username" placeholder="Username"><input id="admin-pass" type="password" autocomplete="current-password" placeholder="Password"><button class="primary-btn" onclick="authenticateAdmin()">Sign in →</button><small id="admin-error" style="color:#ff8d9d"></small></div>`)}
function authenticateAdmin(){const user=document.getElementById('admin-user').value;const pass=document.getElementById('admin-pass').value;if(user===ADMIN_USER&&pass===ADMIN_PASS){sessionStorage.setItem('joboTeenAdmin','1');window.location.href='admin.html'}else document.getElementById('admin-error').textContent='Incorrect username or password.'}
function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function escapeJs(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ')}
function launchPlatform(){document.getElementById('login-screen')?.remove();document.getElementById('main-app')?.style.setProperty('display','flex')}
function notify(message){toast(message)}
function joinMeeting(){toast('Virtual meeting hub is being prepared.')}
function goToAdmin(){openAdminLogin()}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.style.display='none');const target=document.getElementById(id);if(target)target.style.display='block'}
function updateCount(){const i=document.getElementById('life-story-input'),c=document.getElementById('current-chars');if(i&&c)c.textContent=i.value.length}
function saveStory(){toast('Your story has been saved locally.')}

function setTheme(theme){const chosen=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=chosen;localStorage.setItem('joboTeenTheme',chosen);document.querySelectorAll('[data-theme-toggle]').forEach(btn=>{btn.setAttribute('aria-pressed',chosen==='dark');btn.querySelector('.theme-icon')?.replaceChildren(document.createTextNode(chosen==='dark'?'☀':'☾'));const label=btn.querySelector('.theme-label');if(label)label.textContent=chosen==='dark'?'Light':'Dark'});document.querySelector('meta[name="theme-color"]')?.setAttribute('content',chosen==='dark'?'#0b1220':'#2563eb')}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');toast(`${document.documentElement.dataset.theme==='dark'?'Dark':'Light'} theme enabled.`)}
function initTheme(){const saved=localStorage.getItem('joboTeenTheme');const preferred=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(saved||preferred)}
function injectEnhancements(){const css=`
:root{--jt-bg:#f7f9fc;--jt-surface:#fff;--jt-text:#122033;--jt-muted:#65758b;--jt-border:rgba(15,23,42,.09)}
html[data-theme="dark"]{--jt-bg:#07111f;--jt-surface:#101d2d;--jt-text:#edf5ff;--jt-muted:#a9b8cb;--jt-border:rgba(255,255,255,.10);color-scheme:dark}
html[data-theme="dark"] body{background:var(--jt-bg);color:var(--jt-text)}
html[data-theme="dark"] .site-bg{background:radial-gradient(circle at 15% 5%,rgba(37,99,235,.18),transparent 30%),radial-gradient(circle at 90% 20%,rgba(124,58,237,.15),transparent 30%),linear-gradient(180deg,#07111f,#0a1423 60%,#0d1726)}
html[data-theme="dark"] .topbar,html[data-theme="dark"] .glass-card,html[data-theme="dark"] .resource-card,html[data-theme="dark"] .secondary-btn,html[data-theme="dark"] .modal-card{background:rgba(16,29,45,.94);color:var(--jt-text);border-color:var(--jt-border)}
html[data-theme="dark"] .brand,html[data-theme="dark"] .hero h1,html[data-theme="dark"] .section-heading h2,html[data-theme="dark"] .resource-card h3{color:#f5f9ff}html[data-theme="dark"] .hero-copy>p,html[data-theme="dark"] .section-heading>p,html[data-theme="dark"] .muted,html[data-theme="dark"] .resource-card p,html[data-theme="dark"] .modal-card p{color:var(--jt-muted)}
html[data-theme="dark"] .desktop-nav a,html[data-theme="dark"] .ghost-btn,html[data-theme="dark"] .menu-btn{color:#d8e4f2}html[data-theme="dark"] .mobile-nav{background:#0d1929;color:#eef6ff;border-color:var(--jt-border)}html[data-theme="dark"] .mobile-nav a,html[data-theme="dark"] .mobile-nav button{color:#e9f3ff;border-color:var(--jt-border)}
html[data-theme="dark"] .advice-card textarea,html[data-theme="dark"] .advice-card select,html[data-theme="dark"] .modal-form input,html[data-theme="dark"] .modal-form textarea{background:#0a1625;color:#eef6ff;border-color:#26384e}html[data-theme="dark"] .topic-pills button,html[data-theme="dark"] .game-links button{background:#142235;color:#dbe8f7;border-color:#293b51}
.mentor-grid{gap:22px}.mentor-card{min-height:250px;padding:26px!important;border-radius:24px!important;transition:transform .25s ease,box-shadow .25s ease,border-color .25s ease}.mentor-card:hover{transform:translateY(-6px)}.mentor-card .avatar{width:58px;height:58px;border-radius:18px;display:grid;place-items:center;font-weight:900;font-size:1.35rem;margin-bottom:22px;box-shadow:0 12px 30px rgba(0,0,0,.18)}.mentor-card:nth-child(1){border-top:3px solid #38bdf8!important}.mentor-card:nth-child(2){border-top:3px solid #a78bfa!important}.mentor-card:nth-child(3){border-top:3px solid #34d399!important}.mentor-card button{margin-top:10px;border:0;background:transparent;color:#7dd3fc;font-weight:800;cursor:pointer;padding:8px 0}.mentor-card button:hover{color:#fff}.theme-toggle{display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(15,23,42,.12);background:rgba(255,255,255,.72);color:#26364d;border-radius:12px;padding:9px 12px;font-weight:800;cursor:pointer}.theme-toggle:hover{transform:translateY(-1px)}html[data-theme="dark"] .theme-toggle{background:#142235;color:#e7f1ff;border-color:#30435b}.mobile-theme{display:flex!important;align-items:center;gap:10px}.mobile-nav{z-index:1000}.mobile-nav .mobile-nav-head{display:flex;justify-content:space-between;align-items:center;padding:8px 8px 16px;margin-bottom:6px;border-bottom:1px solid var(--jt-border)}.mobile-nav .mobile-nav-head button{font-size:1.5rem;border:0;background:transparent}.mobile-nav a,.mobile-nav>button{display:grid!important;grid-template-columns:30px 1fr;grid-template-rows:auto auto;text-align:left;column-gap:8px;align-items:center}.mobile-nav a small,.mobile-nav>button small{grid-column:2;color:#7b8ca1;font-size:.72rem;margin-top:2px}.mobile-nav a span,.mobile-nav>button span{font-weight:800}.nav-open .mobile-backdrop{display:block}
`;const style=document.createElement('style');style.id='joboteen-enhancements';style.textContent=css;document.head.appendChild(style);if(!document.querySelector('[data-theme-toggle]')){document.querySelectorAll('.top-actions,.mobile-nav').forEach(container=>{const b=document.createElement('button');b.type='button';b.className=container.classList.contains('mobile-nav')?'mobile-theme':'theme-toggle';b.dataset.themeToggle='true';b.onclick=toggleTheme;b.innerHTML='<span class="theme-icon">☾</span><span class="theme-label">Dark</span>';if(container.classList.contains('mobile-nav')){b.innerHTML='<span>◐</span><span class="theme-label">Dark</span><small>Switch appearance</small>'}container.insertBefore(b,container.firstChild)})}}

function showInstallUI(){document.getElementById('install-banner')?.classList.add('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=false;if(m)m.hidden=false}
function dismissInstall(){document.getElementById('install-banner')?.classList.remove('show');sessionStorage.setItem('joboTeenInstallDismissed','1')}
async function installPWA(){if(!deferredInstallPrompt){toast('Use your browser menu and choose “Install app” or “Add to Home screen”.');return}deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;if(choice.outcome==='accepted')toast('JoboTeen is being installed on your device.');deferredInstallPrompt=null;document.getElementById('install-banner')?.classList.remove('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=true;if(m)m.hidden=true}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;if(!sessionStorage.getItem('joboTeenInstallDismissed'))setTimeout(showInstallUI,1800);else showInstallUI()})
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;document.getElementById('install-banner')?.classList.remove('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=true;if(m)m.hidden=true;toast('Welcome to the JoboTeen app.')})

document.addEventListener('DOMContentLoaded',()=>{injectEnhancements();initTheme();const saved=localStorage.getItem('joboTeenName');if(saved)document.title=`JoboTeen — ${saved}`;document.querySelectorAll('#mobile-nav a').forEach(a=>a.addEventListener('click',closeMobileNav));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMobileNav();closeModal()}})})