const ADMIN_USER='admin';
const ADMIN_PASS='admin';
let adviceTopic='';
let deferredInstallPrompt=null;

function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),3200)}
function toggleMobileNav(){const nav=document.getElementById('mobile-nav');if(!nav)return;nav.classList.toggle('show');document.body.classList.toggle('nav-open',nav.classList.contains('show'))}
function closeMobileNav(){document.getElementById('mobile-nav')?.classList.remove('show');document.body.classList.remove('nav-open')}
function openModal(html){const modal=document.getElementById('modal');document.getElementById('modal-content').innerHTML=html;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function closeModal(){const modal=document.getElementById('modal');modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
window.addEventListener('click',e=>{if(e.target.id==='modal')closeModal();if(e.target.classList.contains('mobile-backdrop'))closeMobileNav()})
function chooseTopic(topic){closeMobileNav();document.getElementById('advice')?.scrollIntoView({behavior:'smooth'});setAdviceTopic(null,topic);toast(`Let's talk about ${topic.toLowerCase()}.`)}
function setAdviceTopic(button,topic){adviceTopic=topic;document.querySelectorAll('#topic-pills button').forEach(b=>b.classList.remove('active'));if(button)button.classList.add('active')}
function submitAdvice(){const text=document.getElementById('advice-text')?.value.trim();const urgency=document.getElementById('advice-urgency')?.value;if(!text||text.length<10){toast('Tell us a little more so we can guide you.');return}const request={topic:adviceTopic||'General guidance',message:text,urgency,time:new Date().toISOString(),name:localStorage.getItem('joboTeenName')||'Teen'};const requests=JSON.parse(localStorage.getItem('mentorRequests')||'[]');requests.push(request);localStorage.setItem('mentorRequests',JSON.stringify(requests));const result=document.getElementById('advice-result');result.hidden=false;result.innerHTML='<b>Your request is saved privately on this device.</b><br>For a response from a real mentor, connect JoboTeen to a secure backend.';document.getElementById('advice-text').value='';toast('Your guidance request has been recorded.')}
function openProfile(){const name=localStorage.getItem('joboTeenName')||'';openModal(`<span class="eyebrow">OPTIONAL PROFILE</span><h2>Keep your experience personal.</h2><p>You can use JoboTeen without an account. This optional profile is stored locally on this device.</p><div class="modal-form"><input id="profile-name" value="${escapeHtml(name)}" placeholder="Your first name or nickname"><input id="profile-goal" value="${escapeHtml(localStorage.getItem('joboTeenGoal')||'')}" placeholder="What do you want to work on?"><button class="primary-btn" onclick="saveProfile()">Save my profile</button></div>`)}
function saveProfile(){const name=document.getElementById('profile-name').value.trim();const goal=document.getElementById('profile-goal').value.trim();if(name)localStorage.setItem('joboTeenName',name);if(goal)localStorage.setItem('joboTeenGoal',goal);closeModal();toast('Your optional profile is saved on this device.')}
function openMentor(type){openModal(`<span class="eyebrow">MENTORSHIP</span><h2>${escapeHtml(type)}</h2><p>Tell us what you would like guidance with. You don't need an account to start.</p><div class="modal-form"><textarea id="mentor-message" rows="6" placeholder="What would you like help with?"></textarea><button class="primary-btn" onclick="sendMentorRequest('${escapeJs(type)}')">Send request →</button></div>`)}
function sendMentorRequest(type){const message=document.getElementById('mentor-message').value.trim();if(message.length<10){toast('Please add a little more detail.');return}const requests=JSON.parse(localStorage.getItem('mentorRequests')||'[]');requests.push({mentor:type,message,urgency:'General guidance',time:new Date().toISOString(),name:localStorage.getItem('joboTeenName')||'Anonymous teen'});localStorage.setItem('mentorRequests',JSON.stringify(requests));closeModal();toast('Request saved. A mentor workflow can be connected by the administrator.')}
function openResource(type){const content={study:['Study Skills','Try one focused 25-minute session, then take a short break. Active recall means closing your notes and explaining what you remember. Spaced repetition means revisiting difficult material over time.'],subjects:['Subject Help','Start with the exact question you cannot answer. Break it into known information, unknown information and the concept you need to review.'],life:['Life Skills','Healthy boundaries, clear communication and self-awareness are skills you can practise. Start with one situation and identify what you can control.'],career:['Career Pathways','Think in terms of interests, strengths and problems you enjoy solving. You do not need to choose your entire future today.']};const [title,text]=content[type]||content.life;openModal(`<span class="eyebrow">JOBOTEEN GUIDE</span><h2>${title}</h2><p>${text}</p><div class="modal-form"><button class="primary-btn" onclick="closeModal();document.getElementById('advice').scrollIntoView({behavior:'smooth'})">I want personalised guidance →</button></div>`)}
function readStory(title){const stories={"The Dreamer":'Amira keeps drawing even when classmates mock her. The lesson: criticism can hurt, but it does not have to decide what you become.',"The Choice":'Two friends pressure you to choose a side. Before reacting, consider what is fair, what is safe and what future version of you will respect.',"Behind the Message":'A short message can hide a complicated feeling. Pause before reacting and ask what you may not know yet.'};openModal(`<span class="eyebrow">MIND LIBRARY</span><h2>${escapeHtml(title)}</h2><p>${stories[title]||'A reflection story about growing, choosing and learning.'}</p><p><b>Reflect:</b> What would you do? What could happen next? What would you tell a friend in the same situation?</p><button class="primary-btn" onclick="closeModal();document.getElementById('advice').scrollIntoView({behavior:'smooth'})">Talk it through →</button>`)}
function openGame(path){openModal(`<span class="eyebrow">FUN + LEARNING</span><h2>Game ready</h2><p>Open the cognitive game in a focused window.</p><button class="primary-btn" onclick="window.location.href='${escapeJs(path)}'">Start game →</button>`)}
function openAdminLogin(){openModal(`<span class="eyebrow">RESTRICTED ACCESS</span><h2>Admin dashboard</h2><p>This area is for JoboTeen administrators.</p><div class="modal-form"><input id="admin-user" autocomplete="username" placeholder="Username"><input id="admin-pass" type="password" autocomplete="current-password" placeholder="Password"><button class="primary-btn" onclick="authenticateAdmin()">Sign in →</button><small id="admin-error" style="color:#ff8d9d"></small></div>`)}
function authenticateAdmin(){const user=document.getElementById('admin-user').value;const pass=document.getElementById('admin-pass').value;if(user===ADMIN_USER&&pass===ADMIN_PASS){sessionStorage.setItem('joboTeenAdmin','1');window.location.href='admin.html'}else document.getElementById('admin-error').textContent='Incorrect username or password.'}
function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function escapeJs(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,' ')}
function launchPlatform(){document.getElementById('login-screen')?.remove();document.getElementById('main-app')?.style.setProperty('display','flex')}
function notify(message){toast(message)}
function joinMeeting(){toast('Virtual meeting hub is being prepared.')}
function goToAdmin(){openAdminLogin()}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.style.display='none');const target=document.getElementById(id);if(target)target.style.display='block'}
function updateCount(){const i=document.getElementById('life-story-input'),c=document.getElementById('current-chars');if(i&&c)c.textContent=i.value.length}
function saveStory(){toast('Your story has been saved locally.')}

function setTheme(theme){const chosen=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=chosen;localStorage.setItem('joboTeenTheme',chosen);const btn=document.getElementById('theme-toggle');if(btn){btn.setAttribute('aria-pressed',chosen==='dark');const icon=btn.querySelector('.theme-icon');const label=btn.querySelector('.theme-label');if(icon)icon.textContent=chosen==='dark'?'☀':'☾';if(label)label.textContent=chosen==='dark'?'Light':'Dark'}const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute('content',chosen==='dark'?'#0b1220':'#2563eb')}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');toast(`${document.documentElement.dataset.theme==='dark'?'Dark':'Light'} theme enabled.`)}
function initTheme(){const saved=localStorage.getItem('joboTeenTheme');const preferred=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(saved||preferred)}

function showInstallUI(){document.getElementById('install-banner')?.classList.add('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=false;if(m)m.hidden=false}
function dismissInstall(){document.getElementById('install-banner')?.classList.remove('show');sessionStorage.setItem('joboTeenInstallDismissed','1')}
async function installPWA(){if(!deferredInstallPrompt){toast('Use your browser menu and choose “Install app” or “Add to Home screen”.');return}deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;if(choice.outcome==='accepted')toast('JoboTeen is being installed on your device.');deferredInstallPrompt=null;document.getElementById('install-banner')?.classList.remove('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=true;if(m)m.hidden=true}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;if(!sessionStorage.getItem('joboTeenInstallDismissed'))setTimeout(showInstallUI,1800);else showInstallUI()})
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;document.getElementById('install-banner')?.classList.remove('show');const a=document.getElementById('install-app-btn'),m=document.getElementById('mobile-install-btn');if(a)a.hidden=true;if(m)m.hidden=true;toast('Welcome to the JoboTeen app.')})

document.addEventListener('DOMContentLoaded',()=>{initTheme();const saved=localStorage.getItem('joboTeenName');if(saved)document.title=`JoboTeen — ${saved}`;document.querySelectorAll('#mobile-nav a').forEach(a=>a.addEventListener('click',closeMobileNav));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMobileNav();closeModal()}})})